# https://taskfile.dev

version: '3'

tasks:
  # go
  go/build:
    desc: Build the Go application to ./bin/app
    cmds:
      - CGO_ENABLE=0 go build -o bin/chat ./cmd/chat
    silent: true

  go/run:
    desc: Run the Go application with default settings
    deps: [go/build]
    cmds:
      - ./bin/chat
    silent: true
